<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [1]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [2]:
import folium
import pandas as pd

In [3]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [4]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [5]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [6]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [7]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [13]:
# Initial the map
#site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
for _, row in launch_sites_df.iterrows():
    coords = row.values[1:]
    circle = folium.Circle(coords, radius=1000, color='#d35400', fill=True)
    marker = folium.map.Marker(
    coords,
    #Create an icon as a text label
    icon =DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html=f'<div style="font_size: 12; color:#d35400;"><b>{row[0]}</b></div>',
        ) 
    )
    site_map.add_child(circle)
    site_map.add_child(marker)

site_map

<ipython-input-13-f8188e5eb080>:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  html=f'<div style="font_size: 12; color:#d35400;"><b>{row[0]}</b></div>',

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
   
   * A- Yes, the launch sites are in very close proximity to coasts. Launch sites are often located near the coast for several important reasons
     * 1- Flight Path Over Water: Launching rockets involves inherent risks, including the possibility of failure during ascent. By positioning                launch         sites near the coast, rockets can be directed over the ocean, minimizing the risk to populated areas on land.
     * 2- Stage Separation: Many rockets have multiple stages that separate during ascent. The spent stages typically fall back to Earth. Coastal
          locations allow these stages to drop into the ocean rather than on land, reducing the risk of damage or injury.
   * B- Access to Large Open Areas
     * 1-Unobstructed Launch Path: Coastal areas offer wide, open spaces with fewer obstacles like tall buildings or mountains. This is critical for          ensuring a clear path during launch.
     * 2-Emergency Situations: In case of an emergency or abort scenario, having the ocean nearby provides a safer area for an emergency landing or           splashdown.
   * C- Orbital Mechanics:
     * 1- Proximity to the Equator: Many coastal launch sites are located closer to the equator to take advantage of the Earth's rotational speed.             The Earth's rotation provides an additional boost to the rocket's velocity, making it easier and more fuel-efficient to reach orbit.
     * 2- Flexibility in Launch Trajectories: Coastal locations provide more flexibility in choosing launch trajectories, allowing rockets to reach            a variety of orbits (polar, geostationary, etc.) without overflying populated areas.
   * D- Logistical Considerations:
     * 1- Transportation of Large Components: Rockets and their components are often too large to be transported by road or rail. Coastal locations            allow for the use of ships and barges to transport these massive components directly to the launch site.
    
   * ##### Examples of Coastal Launch Sites:

* 1- Kennedy Space Center, Florida, USA: Located on the east coast, rockets launched from here can head east over the Atlantic Ocean.
* 2- Vandenberg Space Force Base, California, USA: Located on the west coast, this site is ideal for polar orbit launches, with rockets heading           south over the Pacific Ocean.
* 3- Guiana Space Centre, French Guiana: Positioned near the equator, rockets launched from here benefit from the Earth's rotational speed.

  ##### In summary, the proximity of launch sites to the coast is a strategic decision that balances safety, orbital mechanics, and logistical efficiency.



*   Are all launch sites in very close proximity to the coast?


    * No, not all launch sites are located near the Equator. While there are advantages to placing launch sites close to the Equator, there are many       launch sites located at higher latitudes as well. Here's a breakdown of why some launch sites are near the Equator and why others are located        further away:

      #### Advantages of Launch Sites Near the Equator:

      Increased Rotational Velocity: The Earth rotates faster at the Equator (about 1,670 km/h or 1,040 mph), providing rockets with an additional         velocity boost. This makes it easier and more fuel-efficient to reach equatorial orbits and geostationary orbits.
      Efficiency in Reaching Geostationary Orbit: Geostationary orbits are directly above the Equator, so launching from an equatorial site reduces        the energy required to reach this orbit.
      Global Accessibility: Equatorial launch sites can launch rockets to a wide range of orbital inclinations, making them versatile.

     #### Examples of Equatorial Launch Sites:

     Guiana Space Centre (Kourou, French Guiana): Located near the Equator, this site is ideal for launching to geostationary orbit.
     Satish Dhawan Space Centre (India): Also close to the Equator, this site is used for a variety of orbital launches.

     #### Launch Sites Far from the Equator: Many launch sites are located far from the Equator, often for reasons related to national security,          scientific research, or specific orbital needs:

     ##### 1. Polar Orbits:

    Vandenberg Space Force Base (California, USA): Located at 34.7°N, Vandenberg is ideal for launching satellites into polar orbits, which require      a north-south trajectory. These orbits are used for Earth observation satellites that need to pass over the poles to scan the entire surface of      the Earth.
    Plesetsk Cosmodrome (Russia): Located at 62.9°N, this site is used primarily for launching satellites into polar orbits.
    ##### 2. National Security:

    Baikonur Cosmodrome (Kazakhstan): Located at 45.6°N, Baikonur is the world's first and largest operational space launch facility. It was chosen      for strategic reasons during the Soviet era and continues to be a key site for Russian and international launches.

    
    ##### 3. Scientific Research:

    Esrange Space Center (Sweden): Located at 67.9°N, this site is used for launching research rockets and balloons. Its high latitude makes it          ideal for studying the auroras and other phenomena in the polar regions.
    Tanegashima Space Center (Japan): Located at 30.4°N, this site is Japan's primary spaceport. Its location was chosen to maximize safety and          accessibility rather than proximity to the Equator.
   #### Conclusion: While launch sites near the Equator offer specific advantages, particularly for launching satellites into equatorial orbits,         many important launch sites are located at higher latitudes to accommodate different mission profiles, such as polar orbits, national security       considerations, and scientific research. The location of a launch site depends on the specific needs of the missions it serves.

In [ ]:
# Task 2: Mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [14]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [15]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [20]:
# Add marker_cluster to current site_map
marker_cluster = MarkerCluster()
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    icon_color = 'green' if record['class'] else 'red'
    icon= folium.Icon(color=icon_color, icon = 'info-sign')
    marker = folium.Marker(location=[record['Lat'], record['Long']], icon=icon)
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [21]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [22]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [23]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

launch_site_lat, launch_site_lon = 28.563197, -80.576820
coastline_lat, coastline_lon = 28.56319, -80.56785

distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
distance_coastline

0.8762983388668404

In [39]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
def add_distance_marker(site_map, origin, coordinates):
    marker_cluster = MarkerCluster()
    site_map.add_child(marker_cluster)

    for coordinate in coordinates:
        distance = calculate_distance(*origin, *coordinate)

        distance_marker = folium.Marker(
            coordinate,
            icon=DivIcon(
                icon_size=(20,20),
                icon_anchor=(0,0),
                html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
            )
        )
        marker_cluster.add_child(distance_marker)

def add_lines(site_map, origin, coordinates):
    for coordinate in coordinates:
            line=folium.PolyLine(locations=[origin, coordinate], weight=1).add_to(site_map)

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [40]:
coords_df = pd.DataFrame(spacex_df.groupby('Launch Site')[['Lat', 'Long']].max())
coords_df

                    Lat        Long
Launch Site
CCAFS LC-40   28.562302  -80.577356
CCAFS SLC-40  28.563197  -80.576820
KSC LC-39A    28.573255  -80.646895
VAFB SLC-4E   34.632834 -120.610745

In [41]:
origin = coords_df.loc['VAFB SLC-4E'].values
coordinates = [[34.63236, -120.62748]]
add_distance_marker(site_map, origin, coordinates)
add_lines(site_map, origin, coordinates)

origin = coords_df.loc['CCAFS SLC-40'].values
coordinates = [[28.56255, -80.56755]]
add_distance_marker(site_map, origin, coordinates)
add_lines(site_map, origin, coordinates)

site_map

In [ ]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [ ]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

Findings:
💡 Launch sites are strategically located near coastlines for safety, avoiding overflight of populated areas, and enabling water landing in case of an abort.

💡 Proximity to highways and railways ensures efficient transport of cargo and personnel.

💡 Launch sites are intentionally kept at a distance from cities to reduce the risk to densely populated areas, resulting in remote locations with limited infrastructure.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>